server:
  port: 8763

env:
  dev

defaultName:
  jack

spring:
  cloud:
    config:
      uri: http://localhost:8765
      profile: dev
    stream:
      bindings:
        myMessage:
          group: product
          content-type: application/json
  zipkin:
    base-url: http://192.168.1.14:9411/
    sender:
      type: web
    sleuth:
      sampler:
        probability: 1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.14:3306/test?autoReconnect=true&useUnicode=true&createDatabaseIfNotExist=true&characterEncoding=utf8&serverTimezone=UTC

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    com.lucifer.product.dao: debug
