env:
  dev  
server:
  port: 8763
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.160.132:3306/springcloud?autoReconnect=true&useUnicode=true&createDatabaseIfNotExist=true&characterEncoding=utf8&serverTimezone=UTC
eureka:
  instance:
    hostname: order-service
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
